#include "conf.h"
#include "driver/i2s_std.h"
#include "esp_log.h"
#include "global.h"
#include "gpio.h"
#include "isr.h"
#include "tag.h"

// Setup for I2S
// Selects STD mode, sets DMA buffer size and no, sets interrupt callback
void i2s_setup(void) {
  ESP_LOGI(TAG, "I2S setup()");

  i2s_chan_config_t tx_chan_cfg =
      I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_0, I2S_ROLE_MASTER);
  tx_chan_cfg.dma_desc_num = 2;
  tx_chan_cfg.dma_frame_num = DMA_BUFF_SIZE / 4;
  ESP_ERROR_CHECK(i2s_new_channel(&tx_chan_cfg, &tx_chan, NULL));

  /* Step 2: Setting the configurations of standard mode and initialize each
   * channels one by one The slot configuration and clock configuration can be
   * generated by the macros These two helper macros is defined in 'i2s_std.h'
   * which can only be used in STD mode. They can help to specify the slot and
   * clock configurations for initialization or re-configuring */

  // Setup for standard WAV file (16bit, 44.1KHz)
  i2s_std_config_t tx_std_cfg = {
      .clk_cfg = I2S_STD_CLK_DEFAULT_CONFIG(44100),
      .slot_cfg = I2S_STD_PHILIPS_SLOT_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_16BIT,
                                                      I2S_SLOT_MODE_STEREO),
      .gpio_cfg =
          {
              .mclk = I2S_GPIO_UNUSED, // some codecs may require mclk signal,
                                       // this example doesn't need it
              .bclk = BCLK_PIN,
              .ws = WS_PIN,
              .dout = DIN_PIN,
              .din = I2S_GPIO_UNUSED,
              .invert_flags =
                  {
                      .mclk_inv = false,
                      .bclk_inv = false,
                      .ws_inv = false,
                  },
          },
  };
  ESP_ERROR_CHECK(i2s_channel_init_std_mode(tx_chan, &tx_std_cfg));

  // return;
  i2s_event_callbacks_t cbs = {.on_recv = NULL,
                               .on_recv_q_ovf = NULL,
                               .on_sent = i2s_write_callback,
                               .on_send_q_ovf = NULL};
  if ((i2s_channel_register_event_callback(tx_chan, &cbs, NULL)) == ESP_OK) {
    ESP_LOGI(TAG, "i2s_channel_register_callback() OK");
  };
}
